Controllers/SkillController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Skillora.Models.Entities;
using Skillora.Repositories.Interfaces;
using Skillora.Services.Interfaces;
using System;
using System.Linq;

namespace Skillora.Controllers
{
    [Authorize(Roles ="Admin")]
    public class SkillController : Controller
    {
        // GET: SkillController
        private readonly IGenericService<Skill> _skillService;
       
        public SkillController(IGenericService<Skill> skillService)
        {
            _skillService = skillService;
        }

        public ActionResult AdminIndex()
        {
            return View(_skillService.GetAll().ToList());
        }

        // GET: SkillController/Details/5
        public ActionResult Details(string id)
        {
            return View(_skillService.Get(id));
        }
             
        // GET: SkillController/Create
        public ActionResult Create()
        {
            var model = new Skill();
            return View(model);
        }

        // POST: SkillController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Skill model)
        {
            if(ModelState.IsValid)
            {
                try {
                    _skillService.Add(model);
                    return RedirectToAction("AdminIndex");
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
                
            }
            return View();
        }

        // GET: SkillController/Edit/5
        public ActionResult Edit(string id)
        {
            var model = _skillService.Get(id);
            return View(model);
        }

        // POST: SkillController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Skill model)
        {
            if(ModelState.IsValid)
            {
                _skillService.Update(model);
                return RedirectToAction("AdminIndex");
            }
            return View();
        }

        // GET: SkillController/Delete/5
        public ActionResult Delete(string id)
        {
            var model = _skillService.Get(id); 
            return View();
        }

        // POST: SkillController/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            _skillService.Delete(id);
            return RedirectToAction("AdminIndex");
        }
    }
}
  

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Skillora</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @* @if (ViewData["role"]?.ToString() == "Student") *@
            <div class="container">
            @if(User.IsInRole("Student"))
            {
                
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skillora</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                      aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="JobList">Apply for job</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="offeredJob">Job offers</a>
                            </li>

                        </ul>
                    
                </div>
                    <li class="nav-item">
                        <form asp-controller="Account" asp-action="logout" method="post">
                            <input type="submit" value="Logout"/>
                        </form>
                    </li>
            }
            else if(User.IsInRole("Company"))
            {
                
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skillora</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="DisplayByCompany">Job</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="JobStatus" >Job Status</a>
                            </li>

                        </ul>
                    </div>
                    <li class="nav-item">
                        <form asp-controller="Account" asp-action="logout" method="post">
                            <input type="submit" value="Logout" />
                        </form>
                    </li>
                
            }
            else if(User.IsInRole("Admin"))
            {
                
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skillora</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="AdminIndex">Students</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="AdminIndex">Companies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Skill" asp-action="AdminIndex">Skills</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="CompanyApproval">Company Approval</a>
                            </li>

                        </ul>
                    </div>
                    <li class="nav-item">
                        <form asp-controller="Account" asp-action="logout" method="post">
                            <input type="submit" value="Logout" />
                        </form>
                    </li>
                }
</div>                

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Skillora - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>